"""initial schema

Revision ID: 0001
Revises: 
Create Date: 2026-09-16 15:55:20.557714
"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = '0001'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('login', sa.String(length=256), nullable=False),
    sa.Column('full_name', sa.String(length=256), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=True),
    sa.Column('department', sa.String(length=256), nullable=True),
    sa.Column('is_admin', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('login', name=op.f('uq_users_login'))
    )
    op.create_table('employee_profiles',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=True),
    sa.Column('office', sa.String(length=16), server_default=sa.text("'head_office'"), nullable=False),
    sa.Column('full_name', sa.String(length=256), server_default=sa.text("''"), nullable=False),
    sa.Column('position', sa.String(length=256), server_default=sa.text("''"), nullable=False),
    sa.Column('phone', sa.String(length=64), server_default=sa.text("''"), nullable=False),
    sa.Column('order_number', sa.String(length=64), nullable=True),
    sa.Column('order_date', sa.Date(), nullable=True),
    sa.Column('department', sa.String(length=256), server_default=sa.text("''"), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=True),
    sa.Column('no_email', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('account_name', sa.String(length=256), nullable=True),
    sa.Column('pkzi_name', sa.String(length=256), nullable=True),
    sa.Column('manager_full_name', sa.String(length=256), server_default=sa.text("''"), nullable=False),
    sa.Column('manager_position', sa.String(length=256), server_default=sa.text("''"), nullable=False),
    sa.Column('manager_phone', sa.String(length=64), server_default=sa.text("''"), nullable=False),
    sa.Column('vkd_action', sa.String(length=256), nullable=True),
    sa.Column('vkd_rooms', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("office IN ('head_office', 'branch')", name=op.f('ck_employee_profiles_office_valid')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_employee_profiles_user_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_employee_profiles')),
    sa.UniqueConstraint('user_id', name=op.f('uq_employee_profiles_user_id'))
    )
    op.create_table('generated_requests',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('employee_profile_id', sa.BigInteger(), nullable=False),
    sa.Column('system_id', sa.String(length=32), nullable=False),
    sa.Column('action', sa.Text(), nullable=True),
    sa.Column('file_name', sa.String(length=256), nullable=False),
    sa.Column('generated_by_id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['employee_profile_id'], ['employee_profiles.id'], name=op.f('fk_generated_requests_employee_profile_id_employee_profiles'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['generated_by_id'], ['users.id'], name=op.f('fk_generated_requests_generated_by_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_generated_requests'))
    )
    op.create_index(op.f('ix_generated_requests_employee_profile_id'), 'generated_requests', ['employee_profile_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_generated_requests_employee_profile_id'), table_name='generated_requests')
    op.drop_table('generated_requests')
    op.drop_table('employee_profiles')
    op.drop_table('users')
    # ### end Alembic commands ###
